export const DEPOSIT_WALLET_ADDRESS =
  process.env.NEXT_PUBLIC_DEPOSIT_WALLET_ADDRESS ||
  "0x0F49B970d2100C2c1799c8b9993ed3f3B7F6A49A";

export const DEPOSIT_WALLET_NAME = "USDT (ERC-20)";
export const DEPOSIT_WALLET_SYMBOL = "USDT";
export const DEPOSIT_WALLET_NETWORK =
  process.env.NEXT_PUBLIC_WALLET_NETWORK || "Ethereum (ERC-20)";
